import { createApp } from 'vue';
import { createPinia } from 'pinia';
import { ElLoading } from 'element-plus/es/components/loading/index';
import 'element-plus/es/components/alert/style/css';
import 'element-plus/es/components/breadcrumb/style/css';
import 'element-plus/es/components/button/style/css';
import 'element-plus/es/components/card/style/css';
import 'element-plus/es/components/col/style/css';
import 'element-plus/es/components/color-picker/style/css';
import 'element-plus/es/components/container/style/css';
import 'element-plus/es/components/date-picker/style/css';
import 'element-plus/es/components/dialog/style/css';
import 'element-plus/es/components/form/style/css';
import 'element-plus/es/components/icon/style/css';
import 'element-plus/es/components/input/style/css';
import 'element-plus/es/components/input-number/style/css';
import 'element-plus/es/components/loading/style/css';
import 'element-plus/es/components/menu/style/css';
import 'element-plus/es/components/message/style/css';
import 'element-plus/es/components/message-box/style/css';
import 'element-plus/es/components/pagination/style/css';
import 'element-plus/es/components/progress/style/css';
import 'element-plus/es/components/result/style/css';
import 'element-plus/es/components/row/style/css';
import 'element-plus/es/components/scrollbar/style/css';
import 'element-plus/es/components/select/style/css';
import 'element-plus/es/components/switch/style/css';
import 'element-plus/es/components/table/style/css';
import 'element-plus/es/components/tabs/style/css';
import 'element-plus/es/components/tag/style/css';
import 'element-plus/es/components/tooltip/style/css';
import 'element-plus/es/components/upload/style/css';
import App from './App.vue';
import router from './router';
import './styles.css';

const app = createApp(App);

app.use(createPinia()).use(router);
app.use(ElLoading);
app.mount('#app');
